services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d rag_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: rag-it-assistant:latest
    restart: always
    build:
      context: .              # Context à la racine
      dockerfile: Dockerfile  # Dockerfile à la racine
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/rag_db
      - SECRET_KEY=supersecretkeytest
      - HF_TOKEN=${HF_TOKEN}
      - EMBEDDING_MODEL=BAAI/bge-small-en-v1.5
      - LLM_MODEL=google/flan-t5-base
      - PDF_PATH=/app/data/raw/data.pdf
      - CHROMA_PERSIST_DIR=/tmp/chroma
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./app:/app/app  